Repository makerdao/dss, pull requests merged in 2020-11, with the labels that each got.

#164 fix: Update Liquidation Incentive to Use `due`
  src/dog.sol
  src/test/clip.t.sol
Labels: LIQ-2.0, Priority: High, Status: Ready for Review

#165 feat: Upgrade dog, clip to 0.6.7, Update CI (SC-7268)
  .travis.yml
  src/abaci.sol
  src/clip.sol
  src/dog.sol
Labels: LIQ-2.0, Priority: High, Status: Ready for Review

#166 fix: Update incentive comments
  src/dog.sol
Labels: LIQ-2.0, Priority: Medium, Status: Ready for Review

#161 feat: End Integration and `yank()` (SC-6352 + SC-6353)
  src/clip.sol
  src/end.sol
  src/test/clip.t.sol
  src/test/end.t.sol
Labels: LIQ-2.0, Priority: High, Status: Ready for Review

#168 refactor: separate abaci tests
  src/test/abaci.t.sol
  src/test/clip.t.sol
Labels: LIQ-2.0, Priority: Low, Status: Approved

#169 feat: Add `needsRedo` Function (SC-7445)
  src/clip.sol
  src/test/clip.t.sol
Labels: LIQ-2.0, Priority: High, Status: Ready for Review

#167 refactor: Minor `dink` Gas Optimization
  src/dog.sol
Labels: LIQ-2.0, Priority: Medium, Status: Ready for Review
