Repository makerdao/dss, pull requests merged in 2021-03, with the labels that each got.

#210 Fix state mutability warning in one test contract
  src/test/dog.t.sol
Labels: Priority: High, Status: Ready for Review

#213 More efficient lock in case tx reverts or if in future there are not …
  src/clip.sol
Labels: Priority: Critical, Status: Ready for Review

#224 rename getPrice() to getFeedPrice() and price to feedPrice
  src/clip.sol
Labels: LIQ-2.0, Priority: Critical, Status: Ready for Review
