Repository makerdao/dss, pull requests merged in 2021-01, with the labels that each got.

#175 Clipper yank gas opt
  src/clip.sol
  src/test/clip.t.sol
Labels: LIQ-2.0, Priority: Medium

#176 Compile with solc 0.6.11
  .travis.yml
  shell.nix
  src/clip.sol
  src/dog.sol
Labels: Priority: High, Status: Ready for Review

#178 Liq-2.0: remove some whitespace and change to BIL
  src/clip.sol
  src/dog.sol
  src/end.sol
Labels: LIQ-2.0, Priority: Low, Status: Ready for Review, Type: Enhancement

#181 LIQ-2.0 20210114 updates
  Makefile
  src/abaci.sol
  src/clip.sol
  src/dog.sol
Labels: LIQ-2.0, Priority: High, Status: Work In Progress, Type: Enhancement

#184 Liq 2.0 gas improvements
  src/clip.sol
Labels: Priority: High, Status: Ready for Review

#185 Liq 2.0: add tests for external calls
  src/test/clip.t.sol
Labels: LIQ-2.0, Priority: Critical, Status: Ready for Review, Type: Enhancement

#190 Instead of ending auction if tab < dust, recalculate amounts
  src/clip.sol
  src/test/clip.t.sol
Labels: Priority: High, Status: Ready for Review

#188 fix: move incentive to kick() in redo() (SC-8390)
  src/clip.sol
  src/dog.sol
  src/test/clip.t.sol
  src/test/end.t.sol
Labels: LIQ-2.0, Priority: High, Status: Work In Progress, Type: Bug

#186 LIQ-2.0: dusty test cases around dog.bark()
  Makefile
  src/test/dog.t.sol
Labels: LIQ-2.0, Priority: Critical, Status: Ready for Review

#192 Add lock modifier to redo just as extra safety measure
  src/clip.sol
  src/test/clip.t.sol
Labels: Priority: Critical, Status: Ready for Review

#193 Change needsRedo function to getStatus which also includes the price
  src/clip.sol
  src/test/clip.t.sol
Labels: Priority: Critical, Status: Ready for Review

#196 Make chip and tip public + more tests
  src/clip.sol
  src/test/clip.t.sol
Labels: Priority: Critical, Status: Ready for Review
